// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpyfwwglhmqndiypripc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpweWZ3d2dsaG1xbmRpeXByaXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjI4MTIsImV4cCI6MjA2MjkzODgxMn0.9IYnI0E6vDBzzPULNgnPJ_kmNRYO6nGBkRWvo7kW8hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);